INSERT INTO book (
  title,
  author_list_id,
  language_id,
  translator_id,
  original_language_id,
  published_year,
  genre_id,
  subgenre_id,
  format_id
)
values
  (
    {title},
    {author_list_id},
    {language_id},
    {translator_id},
    {original_language_id},
    {published_year},
    {genre_id},
    {subgenre_id},
    {format_id}
  )
;
